### 
POST http://localhost:3000/products/ 
Content-Type: application/json

{
	"title": "Amazing cats",
	"description": "A new product",
	"price": 99
}

###
GET http://localhost:3000/products/ 

###
GET http://localhost:3000/products/00.21422329384303307

### 
PATCH http://localhost:3000/products/00.6437110062858655
Content-Type: application/json

{
	"price": 10
}

###
DELETE http://localhost:3000/products/00.5340857447648666